#!/usr/bin/env python3
# Simple script to interface with nexmo. See nexmo api

from pprint import pprint
import requests
import sys

import nexmo

# mangement url https://dashboard.nexmo.com/
# registered under <email> xxxxxxxxy (eh skype #)
application_id = "xxxxxxxxxxxxxxx"
phone_from = 'xxxxxxxxxy'


def main():
    if len(sys.argv) < 4:
        print(f"Usage: {sys.argv[0]} <phone_to> <subject> <text>")
        print(f'Example: {sys.argv[0]} 1801xxxyyyy "Yo Test" "This is a test"')
        sys.exit()
    phone_to = sys.argv[1]
    subject = sys.argv[2]
    phone_text = sys.argv[3]
    phone_text = subject + phone_text
    private_key = get_nexmo_key()

    call(phone_from, phone_to, phone_text, application_id, private_key)


def get_nexmo_key():
    with open('/var/lib/zabbix/nexmo_000daf9b-ffff-448b-aace-3ecdca27b815_private.key') as f:
        nexmo_key = f.read()
    return nexmo_key


def call(phone_from, phone_to, phone_text, application_id, private_key):
  client = nexmo.Client(
    application_id=application_id,
    private_key=private_key,
  )


  ncco = [
    {
      'action': 'talk',
      'voiceName': 'Kendra',
      'text': phone_text
    }
  ]

  response = client.create_call({
    'to': [{
      'type': 'phone',
      'number': phone_to
    }],
    'from': {
      'type': 'phone',
      'number': phone_from
    },
    'ncco': ncco
  })

  pprint(response)


if __name__ == "__main__":
    main()
